apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  note: Mont Moscow cluster
commonLabels:
  org: RHTE
bases:
- ../../base
patchesStrategicMerge:
- configmap.yaml
- deployment.yaml
- route.yaml
