apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: httpd
  namespace: acm-simple-app
  labels:
    acm: application-meta
    app: httpd
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - httpd
