---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    acm: application-meta
    app: httpd
  name: dev-clusters
  namespace: acm-simple-app
spec:
  clusterSelector:
    matchLabels:
      environment: dev
