apiVersion: v1
kind: Service
metadata:
  labels:
    acm: acm-ha-reverseword
    app: reverseword
  name: reverseword
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: http
    name: http
  selector:
    app: reverseword
#  type: LoadBalancer
