apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    acm: acm-ha-hello
    app: hello
  name: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - image: monopole/hello:1
        command:
        - "/hello"
        - "--port=8080"
        - "--enableRiskyFeature=$(ENABLE_RISKY)"
        ports:
        - containerPort: 8080
        env:
        - name: ALT_GREETING
          valueFrom:
            configMapKeyRef:
              name: parameters
              key: greeting
        - name: ENABLE_RISKY
          valueFrom:
            configMapKeyRef:
              name: monopole
              key: risky
