apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    acm: acm-simple-app
    app: hello
  name: hello
spec:
  host: "<changeme>"
  port:
    targetPort: 8080
  to:
    kind: Service
    name: hello
