apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    acm: acm-ha-reverseword
    app: reverseword
  name: reverseword
spec:
  template:
    spec:
      containers:
      - env:
        - name: RELEASE
          value: "Production release v0.0.2"
        - $patch: replace
        image: quay.io/mavazque/reversewords:v0.0.2
        name: reverseword
