apiVersion: app.k8s.io/v1
#apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  labels:
    acm: application-meta
    app: hello
  name: hello
  namespace: acm-ha-hello
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
        - hello
