apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: master
    apps.open-cluster-management.io/git-path: 510-labs/020-ha-hello/kubernetes/manifest/overlay/moscow
  labels:
    acm: application-meta
    app: hello
  name: app-sub-moscow
  namespace: acm-ha-hello
spec:
  channel: acm-app-channel/hello
  placement:
    placementRef:
      kind: PlacementRule
      name: zone-moscow
