apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  labels:
    acm: application-meta
    app: reverseword
  name: reverseword
  namespace: acm-dr-reverseword
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
        - reverseword
